### ISSUE TITLE
adt-pulse-mqtt gives config warning

### ISSUE THREAD

**Issue by kylefrost** [digitalcraig/adt-pulse-mqtt#10]
Hass.io gives the following Config Warning when running adt-pulse-mqtt:

> Your configuration contains extra keys that the platform does not support (but were silently accepted before 0.88). Please find and remove the following.This will become a breaking change. 
> - [payload_on], [payload_off], [device_class], [value_template].  (See /config/configuration.yaml, line 42).

**Comment by digitalcraig** [comment]
Could you post the relevant part of your configuration.yaml? (line 42)

**Comment by kylefrost** [comment]
Oops, sorry I meant to include that in the first place :upside_down_face:. Here is the WIP alarm_control_panel section:  
```
# ADT Pulse
alarm_control_panel:
  - platform: mqtt
    name: "ADT Pulse"
    state_topic: "home/alarm/state"
    command_topic: "home/alarm/cmd"
    payload_arm_home: "arm_home"
    payload_arm_away: "arm_away"
    payload_disarm: "disarm"
  - platform: mqtt
    name: "Kitchen Door"
    state_topic: "adt/zone/Kitchen Door/state"
    payload_on: "devStatOpen"
    payload_off: "devStatOK"
    command_topic: "home/alarm/cmd"
    device_class: door
    retain: true
    value_template: '{{ value_json.status }}'
```
  
Line 42 is the second `- platform: mqtt` line, for the Kitchen Door part.

**Comment by digitalcraig** [comment]
You want to put the door sensors under binary_sensor (with other binary_sensors if you have them) and not alarm_panel. Also, remove the command_topic since binary sensors don't support commands. See https://www.home-assistant.io/components/binary_sensor.mqtt/

Here is my configuration:

```
# MQTT Alarm
alarm_control_panel:
  - platform: mqtt
    name: "ADT Pulse"
    state_topic: "home/alarm/state"
    command_topic: "home/alarm/cmd"
    payload_arm_home: "arm_home"
    payload_arm_away: "arm_away"
    payload_disarm: "disarm"
```
.
.
.
```
binary_sensor:
  #ADT Alarm Zones
  - platform: mqtt
    name: "Back Door"
    state_topic: "adt/zone/BACK DOOR/state"
    payload_on: "devStatOpen" # Use devStatTamper for shock devices
    payload_off: "devStatOK" #
    device_class: door
    value_template: '{{ value_json.status }}'
  - platform: mqtt
    name: "Front Door"
    state_topic: "adt/zone/FRONT DOOR/state"
    payload_on: "devStatOpen" # Use devStatTamper for shock devices
    payload_off: "devStatOK" #
    device_class: door
    value_template: '{{ value_json.status }}'
  - platform: mqtt
    name: "Garage Door"
    state_topic: "adt/zone/GARAGE DOOR/state"
    payload_on: "devStatOpen" # Use devStatTamper for shock devices
    payload_off: "devStatOK" #
    device_class: door
    value_template: '{{ value_json.status }}'
```
