### ISSUE TITLE
Possible to use without HASSIO?

### ISSUE THREAD

**Issue by robross0606** [digitalcraig/adt-pulse-mqtt#14]
Is it possible to install and use this without HASSIO?  I have Home Assistant installed on a PC and SmartThings, but not an rPi or HASSIO.  Instructions on setting up manually would be helpful.

**Comment by digitalcraig** [comment]
Yes, you can pull down the docker container for your architecture to your Docker host See https://hub.docker.com/r/digitalcraig/adt-pulse-mqtt/tags. You will need to define a persistent volume at /data to hold the options.json file.

Here is an example docker-compose.yml file:

```
version: '3'
services:
   pulse-adt-mqtt:
      container_name: pulse-adt-mqtt
      image: digitalcraig/adt-pulse-mqtt
      network_mode: host
      restart: always
      volumes:
       - /share/Container/pulse-adt-mqtt-config:/data
```
Here is a sample options.json file:

```
{
      "pulse_login" : {
        "username": "username",
        "password": "password"
      },
      "mqtt_url" : "mqtt://mqtt:1883",
      "mqtt_connect_options" :  {
        "username" : "username",
        "password" : "password",
		"clientId" : "adtpulse",
		"protocolId" : "MQIsdp",
		"protocolVersion" : "3",
		"connectTimeout" : "1000",
		"debug" : "true"
      },
      "alarm_state_topic": "home/alarm/state",
      "alarm_command_topic": "home/alarm/cmd",
      "zone_state_topic": "adt/zone",
      "smartthings_topic": "smartthings",
      "smartthings": false
}
```

If you aren't comfortable with Docker, there is also now a native ADT integration for Home Assistant being developed by Ryan Snodgrass. See https://community.home-assistant.io/t/adt-pulse-integration/10160/210 and https://github.com/rsnodgrass/hass-adtpulse/.
