### ISSUE TITLE
Error Parsing Value

### ISSUE THREAD

**Issue by jrdean** [digitalcraig/adt-pulse-mqtt#22]
This add on is working perfectly for me since it was updated in March. 

I am however getting an alarming number of errors reported in the Developer Tools - Logs. Approximately 800 errors per hour. Here is the details about the error:
```
Log Details (ERROR)
Logger: homeassistant.helpers.template
Source: helpers/template.py:283
First occurred: April 21, 2020, 11:21:44 AM (23586 occurrences)
Last logged: 3:19:35 PM

Error parsing value: 'value_json' is undefined (value: devStatOK, template: {{ value_json.status }})
Error parsing value: 'value_json' is undefined (value: devStatMotion, template: {{ value_json.status }})
Error parsing value: 'value_json' is undefined (value: devStatOpen, template: {{ value_json.status }})

```
I don't think the error is caused by this, but I do want to mention that I was unable to get the green check mark when I check the configuration of my config.yaml using the MQTT binary sensor sample given in the ADT Pulse MQTT readme file. The variable "    retain: true" was giving me errors so I deleted that line from each of my sensors. It passed the configuration check and like I said has been working and reporting sensor stats perfectly since March. Here are the sensors I created in my config.yaml.
```
binary_sensor:

  - platform: mqtt
    name: "Garage Door mqtt"
    state_topic: "adt/zone/GARAGE DOOR/state"
    payload_on: "devStatOpen" # Use devStatTamper for shock devices
    payload_off: "devStatOK" # 
    device_class: door
    value_template: '{{ value_json.status }}' 
  - platform: mqtt
    name: "Front Door mqtt"
    state_topic: "adt/zone/FRONT DOOR/state"
    payload_on: "devStatOpen" # Use devStatTamper for shock devices
    payload_off: "devStatOK" # 
    device_class: door
    value_template: '{{ value_json.status }}'
  - platform: mqtt
    name: "Living Room and Den Doors mqtt"
    state_topic: "adt/zone/LIVING ROOM AND DEN DOORS/state"
    payload_on: "devStatOpen" # Use devStatTamper for shock devices
    payload_off: "devStatOK" # 
    device_class: door
    value_template: '{{ value_json.status }}' 
  - platform: mqtt
    name: "Motion 2nd Floor mqtt"
    state_topic: "adt/zone/2ND FLOOR MOTION DETECTOR/state"
    payload_on: "devStatMotion" # Use devStatTamper for shock devices
    payload_off: "devStatOK" # 
    device_class: motion
    value_template: '{{ value_json.status }}' 
  - platform: mqtt
    name: "Motion Foyer mqtt"
    state_topic: "adt/zone/FOYER MOTION DETECTOR/state"
    payload_on: "devStatMotion" # Use devStatTamper for shock devices
    payload_off: "devStatOK" # 
    device_class: motion
    value_template: '{{ value_json.status }}' 
  - platform: mqtt
    name: "Motion Family Room mqtt"
    state_topic: "adt/zone/DEN MOTION DETECTOR/state"
    payload_on: "devStatMotion" # Use devStatTamper for shock devices
    payload_off: "devStatOK" # 
    device_class: motion
    value_template: '{{ value_json.status }}'
  - platform: mqtt
    name: "2nd Floor Smoke Detector mqtt"
    state_topic: "adt/zone/2ND FLOOR SMOKE DETECTOR/state"
    payload_on: "devStatAlarm" # Use devStatTamper for shock devices
    payload_off: "devStatOK" # 
    device_class: smoke
    value_template: '{{ value_json.status }}'
  - platform: mqtt
    name: "Den Glass Break mqtt"
    state_topic: "adt/zone/DEN GLASS BREAK DETECTOR/state"
    payload_on: "devStatTamper" # Use devStatTamper for shock devices
    payload_off: "devStatOK" # 
    device_class: problem
    value_template: '{{ value_json.status }}'
  - platform: mqtt
    name: "Living Room Glass Break mqtt"
    state_topic: "adt/zone/LIVING ROOM GLASS BREAK DETECT/state"
    payload_on: "devStatTamper" # Use devStatTamper for shock devices
    payload_off: "devStatOK" # 
    device_class: problem
    value_template: '{{ value_json.status }}'
  - platform: mqtt
    name: "Master Bath Glass Break mqtt"
    state_topic: "adt/zone/MASTER BATH GLASS BREAK/state"
    payload_on: "devStatTamper" # Use devStatTamper for shock devices
    payload_off: "devStatOK" # 
    device_class: problem
    value_template: '{{ value_json.status }}'
```

Everything in the ADT Pulse MQTT add on log looks good to me. 

```
4/22/2020, 3:34:51 PM Pulse.Sync: Syncing 28824-0-0
4/22/2020, 3:34:56 PM Pulse.Sync: Syncing 1-0-0
4/22/2020, 3:34:56 PM Pulse: updateAll
4/22/2020, 3:34:56 PM Pulse.getAlarmStatus: Getting Alarm Statuses
4/22/2020, 3:34:56 PM Pulse.getDeviceStatus: Getting Device Statuses
4/22/2020, 3:34:56 PM Pulse.getZoneStatus(via Orb): Getting Zone Statuses
4/22/2020, 3:34:56 PM Pulse.getDeviceStatus No other devices found
4/22/2020, 3:34:57 PMADT Pulse: Get zone status (via orb) success.
4/22/2020, 3:34:57 PM Sensor: sensor-6 Name: 2ND FLOOR MOTION DETECTOR Tags: sensor State devStatOK
4/22/2020, 3:34:57 PM: Pushing device state: devStatOK to topic adt/zone/2ND FLOOR MOTION DETECTOR/state
4/22/2020, 3:34:57 PM Sensor: sensor-10 Name: 2ND FLOOR SMOKE DETECTOR Tags: sensor State devStatOK
4/22/2020, 3:34:57 PM: Pushing device state: devStatOK to topic adt/zone/2ND FLOOR SMOKE DETECTOR/state
4/22/2020, 3:34:57 PM Sensor: sensor-8 Name: DEN GLASS BREAK DETECTOR Tags: sensor State devStatOK
4/22/2020, 3:34:57 PM: Pushing device state: devStatOK to topic adt/zone/DEN GLASS BREAK DETECTOR/state
4/22/2020, 3:34:57 PM Sensor: sensor-4 Name: DEN MOTION DETECTOR Tags: sensor State devStatOK
4/22/2020, 3:34:57 PM: Pushing device state: devStatOK to topic adt/zone/DEN MOTION DETECTOR/state
4/22/2020, 3:34:57 PM Sensor: sensor-5 Name: FOYER MOTION DETECTOR Tags: sensor State devStatOK
4/22/2020, 3:34:57 PM: Pushing device state: devStatOK to topic adt/zone/FOYER MOTION DETECTOR/state
4/22/2020, 3:34:57 PM Sensor: sensor-1 Name: FRONT DOOR Tags: sensor State devStatOK
4/22/2020, 3:34:57 PM: Pushing device state: devStatOK to topic adt/zone/FRONT DOOR/state
4/22/2020, 3:34:57 PM Sensor: sensor-2 Name: GARAGE DOOR Tags: sensor State devStatOK
4/22/2020, 3:34:57 PM: Pushing device state: devStatOK to topic adt/zone/GARAGE DOOR/state
4/22/2020, 3:34:57 PM Sensor: sensor-3 Name: LIVING ROOM AND DEN DOORS Tags: sensor State devStatOK
4/22/2020, 3:34:57 PM: Pushing device state: devStatOK to topic adt/zone/LIVING ROOM AND DEN DOORS/state
4/22/2020, 3:34:57 PM Sensor: sensor-7 Name: LIVING ROOM GLASS BREAK DETECT Tags: sensor State devStatOK
4/22/2020, 3:34:57 PM: Pushing device state: devStatOK to topic adt/zone/LIVING ROOM GLASS BREAK DETECT/state
4/22/2020, 3:34:57 PM Sensor: sensor-9 Name: MASTER BATH GLASS BREAK Tags: sensor State devStatOK
4/22/2020, 3:34:57 PM: Pushing device state: devStatOK to topic adt/zone/MASTER BATH GLASS BREAK/state
4/22/2020, 3:35:01 PM Pulse.Sync: Syncing 28825-0-0
4/22/2020, 3:35:01 PM Pulse: updateAll
4/22/2020, 3:35:01 PM Pulse.getAlarmStatus: Getting Alarm Statuses
4/22/2020, 3:35:01 PM Pulse.getDeviceStatus: Getting Device Statuses
4/22/2020, 3:35:01 PM Pulse.getZoneStatus(via Orb): Getting Zone Statuses
4/22/2020, 3:35:01 PM Pulse.getDeviceStatus No other devices found
4/22/2020, 3:35:02 PMADT Pulse: Get zone status (via orb) success.
4/22/2020, 3:35:02 PM Sensor: sensor-6 Name: 2ND FLOOR MOTION DETECTOR Tags: sensor State devStatOK
4/22/2020, 3:35:02 PM: Pushing device state: devStatOK to topic adt/zone/2ND FLOOR MOTION DETECTOR/state
4/22/2020, 3:35:02 PM Sensor: sensor-10 Name: 2ND FLOOR SMOKE DETECTOR Tags: sensor State devStatOK
4/22/2020, 3:35:02 PM: Pushing device state: devStatOK to topic adt/zone/2ND FLOOR SMOKE DETECTOR/state
4/22/2020, 3:35:02 PM Sensor: sensor-8 Name: DEN GLASS BREAK DETECTOR Tags: sensor State devStatOK
4/22/2020, 3:35:02 PM: Pushing device state: devStatOK to topic adt/zone/DEN GLASS BREAK DETECTOR/state
4/22/2020, 3:35:02 PM Sensor: sensor-4 Name: DEN MOTION DETECTOR Tags: sensor State devStatOK
4/22/2020, 3:35:02 PM: Pushing device state: devStatOK to topic adt/zone/DEN MOTION DETECTOR/state
4/22/2020, 3:35:02 PM Sensor: sensor-5 Name: FOYER MOTION DETECTOR Tags: sensor State devStatOK
4/22/2020, 3:35:02 PM: Pushing device state: devStatOK to topic adt/zone/FOYER MOTION DETECTOR/state
4/22/2020, 3:35:02 PM Sensor: sensor-1 Name: FRONT DOOR Tags: sensor State devStatOK
4/22/2020, 3:35:02 PM: Pushing device state: devStatOK to topic adt/zone/FRONT DOOR/state
4/22/2020, 3:35:02 PM Sensor: sensor-2 Name: GARAGE DOOR Tags: sensor State devStatOK
4/22/2020, 3:35:02 PM: Pushing device state: devStatOK to topic adt/zone/GARAGE DOOR/state
4/22/2020, 3:35:02 PM Sensor: sensor-3 Name: LIVING ROOM AND DEN DOORS Tags: sensor State devStatOK
4/22/2020, 3:35:02 PM: Pushing device state: devStatOK to topic adt/zone/LIVING ROOM AND DEN DOORS/state
4/22/2020, 3:35:02 PM Sensor: sensor-7 Name: LIVING ROOM GLASS BREAK DETECT Tags: sensor State devStatOK
4/22/2020, 3:35:02 PM: Pushing device state: devStatOK to topic adt/zone/LIVING ROOM GLASS BREAK DETECT/state
4/22/2020, 3:35:02 PM Sensor: sensor-9 Name: MASTER BATH GLASS BREAK Tags: sensor State devStatOK
4/22/2020, 3:35:02 PM: Pushing device state: devStatOK to topic adt/zone/MASTER BATH GLASS BREAK/state
4/22/2020, 3:35:06 PM Pulse.Sync: Syncing 28825-0-0
4/22/2020, 3:35:11 PM Pulse.Sync: Syncing 28825-0-0
4/22/2020, 3:35:16 PM Pulse.Sync: Syncing 28825-0-0
```
Is there something that I've done wrong on my end? Is it safe to simply ignore these errors?
