### ISSUE TITLE
How to use without "Supervisor" HASS?

### ISSUE THREAD

**Issue by robross0606** [digitalcraig/adt-pulse-mqtt#28]
If you're using HASS core instead of HASSIO ("Supervised"), how do you install this add-on?

**Comment by digitalcraig** [comment]
The recommended method is to run ADT Pulse MQTT as a Docker container and it needs an MQTT server to communicate with Home Assistant. If you are also running Home Assistant in Docker, the easiest way to coordinate running multiple containers is with Docker Compose. You would create a docker-compose.yml file and run "docker-compose up -d' in that directory to start everything.

Here's a sample docker-compose.yml file that I use on QNAP Container Station which includes services for Home Assistant, MQTT, and ADT Pulse MQTT. You would change the paths to your configuration directories accordingly. Also, I've changed the tags on the images to latest, but it is recommended practice to use specific version tags (e.g. digitalcraig/adt-pulse-mqtt:v2.3.0 or digitalcraig/adt-pulse-mqtt:v2.3.0-armhf) depending on if you are running on a Raspberry Pi or not. The same for Home Assistant so you can control when you upgrade to a newer image.

```
version: '3'
services:
   mqtt:
      container_name: mqtt
      image: eclipse-mosquitto:latest
      network_mode: host
      volumes:
       - /share/Container/mosquitto-config:/mosquitto/config
       - /share/Container/mosquitto-ssl:/ssl
      restart: always
      ports:
       - "8883:8883"
       - "1883:1883"
   adt-pulse-mqtt:
      container_name: adt-pulse-mqtt
      image: digitalcraig/adt-pulse-mqtt:latest
      network_mode: host
      restart: always
      volumes:
       - /share/Container/pulse-adt-mqtt-config:/data
       - /share/Container/mosquitto-ssl:/ssl
   homeassistant:
      container_name: home-assistant
      image: homeassistant/home-assistant:latest
      network_mode: host
      volumes:
        - /share/Container/hassio-config:/config
        - /share/Container/mosquitto-ssl:/ssl
        - /etc/localtime:/etc/localtime:ro
      depends_on:
        - mqtt
        - influxdb
      restart: always
      ports:
        - "8123:8123"

```
